### ISSUE TITLE
Codemirror is overflowing code result container

### ISSUE THREAD

**Issue by gsilvamartin** [gsilvamartin/RTCode#30]
**Describe the bug**

Codemirror is overflowing code result container

**To Reproduce**

1. Go to Code
2. Click on Options.
3. Change theme
4. Close modal
5. Click on code editor
6. See error

**Screenshots**

**Overflow:**

![image](https://user-images.githubusercontent.com/42881020/71368089-ad80d100-2585-11ea-8b66-458e13b866ed.png)

**Expected:**

![image](https://user-images.githubusercontent.com/42881020/71368118-c4bfbe80-2585-11ea-9f5a-95d895d0cb74.png)

**Comment by MatheusMuriel** [comment]
https://github.com/gsilvamartin/RTCode/commit/9a2aef12ead7d72717e23454dee9f148cd69ae0b

**Comment by MatheusMuriel** [comment]
https://github.com/gsilvamartin/RTCode/commit/b35d6f1cbaa41afe8473a6743fe8a9036c91ec55
