### ISSUE TITLE
TypeError: Cannot read property 'stdin' of undefined

### ISSUE THREAD

**Issue by DenSA-Inc** [gsilvamartin/RTCode#39]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/gsilvamartin/RTCode/issues) Checked

**Describe the bug**

I'm trying to run the latest version of the backend but it keeps crashing with the following error:
```
root@eb941684c20c:/cwd# npm start

> rt-code@1.0.1 start /cwd
> node ./Back-end/controller/Main.js

/cwd/Back-end/controller/Main.js:96
    terminalSession.stdin.setEncoding('utf8');
                    ^

TypeError: Cannot read property 'stdin' of undefined
    at Socket.<anonymous> (/cwd/Back-end/controller/Main.js:96:21)
    at Socket.emit (events.js:305:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at /cwd/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rt-code@1.0.1 start: `node ./Back-end/controller/Main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rt-code@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-26T16_33_18_306Z-debug.log
```
(this was a docker-container with node 13.5.0, but i was also able to replicate it with node 10.17.0 outside of docker)

**To Reproduce**

1. Install and run the application just as described in the readme
2. Open your browser at http://localhost:5000/code/
3. Create a new code and choose "C" as language
4. Watch the server crash after some interaction with the website

**Expected behavior**

A server should not crash

**Screenshots**

See error-message above

**Environment (please complete the following information):**

- OS: Linux (Ubuntu 18.04)
- Navigator: Mozilla Firefox

I found that [this function](https://github.com/gsilvamartin/RTCode/blob/163a7fe1e0c758096ca0fb1e694df768810f8a55/Back-end/service/REPLService.js#L18) does not return anything when passed "C" as `language`. That causes the whole server-process to crash, you should catch that error at some level to avoid that.
You should return some value to the user that indicates something is wrong, similar to a HTTP-500.

**Comment by gsilvamartin** [comment]
Hello, thank you very much for participating!

I will be including more languages for execution and I do error handling this function.

**Comment by gsilvamartin** [comment]
Hi, I made the changes and uploaded it to the master branch.
