### ISSUE TITLE
Build frontend in Vue

### ISSUE THREAD

**Issue by MatheusMuriel** [gsilvamartin/RTCode#53]
Build and test a frontend with VueJS + Webpack

**Comment by MatheusMuriel** [comment]
Branch: https://github.com/gsilvamartin/RTCode/tree/refactory-front-vue

**Comment by MatheusMuriel** [comment]
Components: Ok

**Comment by MatheusMuriel** [comment]
XtermJS and LocalEcho: Ok

**Comment by MatheusMuriel** [comment]
Monaco Editor: Ok

**Comment by marko-ignjatovic** [comment]
Guys what about font-awesome icons? Are those loaded somehow?

**Comment by MatheusMuriel** [comment]
Not implemented yet, but if you want you can implement yourself :D
